const fs = require('fs');
const path = require('path');
const readline = require('readline');

const ARGS = process.argv.slice(2); 
const COMMAND = ARGS[0];
const TARGET_NAME = ARGS[1];
const APP_JS_PATH = path.join(__dirname, '../src/App.js');

const GREEN = '\x1b[32m';
const RED = '\x1b[31m';
const BLUE = '\x1b[36m';
const YELLOW = '\x1b[33m';
const RESET = '\x1b[0m';

const getTemplate = (pageName) => `import React, { useState, useEffect } from 'react';
import { fleetboDB } from 'config/fleetboConfig';
import PageConfig from 'components/common/PageConfig';
import Loader from 'components/common/Loader';
import { ArrowLeftCircle } from 'lucide-react';

const ${pageName}Header = ({ onBack }) => (
    <header className='navbar ps-3 pt-3'>
        <div>
            <button onClick={onBack} className="btn-header text-success fs-5 fw-bold d-flex align-items-center">
                <ArrowLeftCircle /> <span className='ms-3'>${pageName}</span>
            </button>
        </div>
    </header>
);

const ${pageName} = () => {
    const [loading, setLoading] = useState(false);
    const [error, setError]     = useState("");

    useEffect(() => {
        // loadData();
    }, []);

    return (
        <>
            <PageConfig navbar="none" />
            
            <${pageName}Header onBack={() => Fleetbo.back()} />

            <div className="p-3 fade-in">
                <div className="text-center mt-5">
                    <h3 className="text-secondary">${pageName}</h3>
                    <p className="text-muted small">Generated by Fleetbo CLI</p>
                </div>
            </div>
        </>
    );
};

export default ${pageName};
`;

const injectIntoAppJs = (pageName, importPath, routePath) => {
    if (!fs.existsSync(APP_JS_PATH)) return false;

    let content = fs.readFileSync(APP_JS_PATH, 'utf8');

    if (!content.includes('// FLEETBO_IMPORTS') || !content.includes('// FLEETBO_ROUTES')) {
        console.log(`${YELLOW}  Anchors not found in App.js. Skipping auto-wiring.${RESET}`);
        return false;
    }

    const cleanImport = importPath ? `/${importPath}` : '';
    const importLine = `import ${pageName} from './pages${cleanImport}/${pageName}';`; 
    const routeLine = `<Route path="/${routePath}" element={<${pageName} />} />`;

    let injected = false;

    if (!content.includes(importLine)) {
        content = content.replace('// FLEETBO_IMPORTS', `${importLine}\n// FLEETBO_IMPORTS`);
        injected = true;
    }

    if (!content.includes(routeLine)) {
        const anchor = content.includes('{/* FLEETBO_ROUTES */}') ? '{/* FLEETBO_ROUTES */}' : '// FLEETBO_ROUTES';
        content = content.replace(anchor, `${routeLine}\n        ${anchor}`);
        injected = true;
    }

    if (injected) fs.writeFileSync(APP_JS_PATH, content);
    return injected;
};

const runPageGenerator = (inputPath) => {
    if (!inputPath) {
        const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
        rl.question(`${BLUE} Enter Page Path (e.g. admin/Settings): ${RESET}`, (n) => { 
            if(n) runPageGenerator(n); 
            rl.close(); 
        });
        return;
    }

    const parts = inputPath.split(/[/\\]/); 
    const rawName = parts.pop(); 
    const subDir = parts.join('/'); 

    const pageName = rawName.charAt(0).toUpperCase() + rawName.slice(1);
    const baseDir = path.join(__dirname, '../src/pages');
    const targetDir = path.join(baseDir, subDir);
    const filePath = path.join(targetDir, `${pageName}.jsx`);

    if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });

    if (fs.existsSync(filePath)) {
        console.log(`${RED}  Error: Page "${pageName}" already exists!${RESET}`);
        process.exit(1);
    }

    fs.writeFileSync(filePath, getTemplate(pageName));

    const routePath = subDir ? `${subDir}/${pageName.toLowerCase()}` : `${pageName.toLowerCase()}`;
    const injected = injectIntoAppJs(pageName, subDir, routePath);

    console.log(`
${GREEN}  FLEETBO PAGE GENERATED${RESET}
    📂 ${BLUE}src/pages/${subDir ? subDir + '/' : ''}${pageName}.jsx${RESET}`);

    if (injected) {
        console.log(`   App.js updated: Route /${routePath}`);
    } else {
        console.log(`   Add route manually in App.js`);
    }
};

const main = () => {
    switch (COMMAND) {
        case 'page':
        case 'g': 
            runPageGenerator(TARGET_NAME);
            break;
        
        default:
            console.log(`
${BLUE} FLEETBO CLI${RESET}
    -------------------
    Usage:
    ${GREEN}npm run fleetbo page [Name]${RESET}
    ${GREEN}npm run fleetbo page [Folder/Name]${RESET}
            `);
            break;
    }
};

main();
